version: '3.4'
services:

  leprikon:
    image: misli/zoobrno
    build: .
    depends_on:
      - mysql
      - redis
      - smtp
    environment:
      DATABASE_ENGINE: django.db.backends.mysql
      DATABASE_HOST: ''
      DATABASE_NAME: zoobrno
      DATABASE_USER: zoobrno
      DATABASE_PASSWORD: dbpassword
      EMAIL_HOST: smtp
      EMAIL_HOST_USER: zoobrno
      EMAIL_HOST_PASSWORD: emailpassword
      EMAIL_SUBJECT_PREFIX: '[Zoo Brno]'
      LEPRIKON_VARIABLE_SYMBOL_EXPRESSION: '30000000 + reg.subject.subject_type_id * 1000000 + (reg.created.year % 100) * 10000 + (reg.id % 10000)'
      CACHE_LOCATION: unix:///var/run/redis/redis.sock
      SECRET_KEY: secretkey
      SENTRY_ENVIRONMENT: 'zoobrno'
      SERVER_EMAIL: '"Zoo Brno" <vzdelavanizoo@zoobrno.cz>'
    ports:
      - 127.0.0.1:10050:80
    volumes:
      - ./data:/app/data
      - ./media:/app/htdocs/media
      - mysql:/var/run/mysqld
      - redis:/var/run/redis

  redis:
    image: redis
    command: bash -c "chmod 0777 /var/run/redis && redis-server --appendonly yes --unixsocket /var/run/redis/redis.sock --unixsocketperm 777"
    volumes:
      - ./redis:/data
      - redis:/var/run/redis

  mysql:
    image: mariadb
    environment:
      MYSQL_DATABASE: zoobrno
      MYSQL_USER: zoobrno
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: rootdbpassword
    volumes:
      - mysql:/var/run/mysqld
      - ./mysql:/var/lib/mysql

  smtp:
    image: catatnight/postfix
    environment:
      maildomain: zoobrno.cz
      smtp_user: zoobrno:emailpassword
    stdin_open: true
    tty: true
    volumes:
      - ./dkim:/etc/opendkim/domainkeys

volumes:
  mysql:
  redis:
