version: '3.4'

x-leprikon: &leprikon
  image: qbsoftware/zoobrno
  depends_on:
    - mysql
    - redis
    - smtprelay
  environment:
    DATABASE_ENGINE: django.db.backends.mysql
    DATABASE_HOST: ''
    DATABASE_NAME: zoobrno
    DATABASE_USER: zoobrno
    DATABASE_PASSWORD: dbpassword
    EMAIL_HOST: smtprelay
    EMAIL_SUBJECT_PREFIX: '[Zoo Brno]'
    LEPRIKON_VARIABLE_SYMBOL_EXPRESSION: '30000000 + reg.subject.subject_type_id * 1000000 + (reg.created.year % 100) * 10000 + (reg.id % 10000)'
    CACHE_LOCATION: unix:///var/run/redis/redis.sock
    SECRET_KEY: secretkey
    SENTRY_ENVIRONMENT: 'zoobrno'
    SERVER_EMAIL: '"Zoo Brno" <zoobrno@leprikon.cz>'
    SUPERVISORD_RUN: "gunicorn cron"
    GUNICORN_WORKERS: "9"
  volumes:
    - ./data:/app/data
    - ./media:/app/htdocs/media
    - ./static:/app/htdocs/static
    - ./run:/app/run
    - ./templates:/app/templates
    - mysql:/var/run/mysqld
    - redis:/var/run/redis

services:

  leprikon:
    <<: *leprikon
    build: .

  leprikon-collectstatic:
    <<: *leprikon
    command: leprikon collectstatic --no-input

  redis:
    image: redis
    command: bash -c "chmod 0777 /var/run/redis && redis-server --appendonly yes --unixsocket /var/run/redis/redis.sock --unixsocketperm 777"
    volumes:
      - ./redis:/data
      - redis:/var/run/redis

  mysql:
    image: mariadb
    environment:
      MYSQL_DATABASE: zoobrno
      MYSQL_USER: zoobrno
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: rootdbpassword
    volumes:
      - mysql:/var/run/mysqld
      - ./mysql:/var/lib/mysql

  smtprelay:
    image: juanluisbaptiste/postfix
    environment:
      SERVER_HOSTNAME: leprikon.cz
      SMTP_SERVER: smtp.savana.cz
      SMTP_PORT: 465
      SMTP_USERNAME: zoobrno@leprikon.cz
      SMTP_PASSWORD: emailpassword

volumes:
  mysql:
  redis:
